import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
const timeline = readFileSync(new URL('../src/components/Timeline.astro', import.meta.url), 'utf8');
const timelinePage = readFileSync(new URL('../src/pages/timeline.astro', import.meta.url), 'utf8');
const policyRoute = readFileSync(new URL('../src/pages/policies/[id].astro', import.meta.url), 'utf8');
test('Timeline retains a complete no-JavaScript chronology and escapes embedded data', () => { assert.match(timeline, /data-timeline-list/); assert.match(timeline, /<noscript>/); assert.match(timeline, /aria-live="polite"/); assert.match(timeline, /data-timeline-entry/); assert.ok(timelinePage.includes('<Timeline data={data} />')); });
test('Timeline defaults to principal records and offers all documents and versions', () => { assert.match(timeline, /value="principal"[^>]*checked/); assert.match(timeline, /Principal documents/); assert.match(timeline, /value="all"/); assert.match(timeline, /All documents and versions/); });
test('policy routes are generated from published data and distinguish official and analytical content', () => { assert.match(policyRoute, /export function getStaticPaths/); assert.match(policyRoute, /Research-defined policy grouping/); assert.match(policyRoute, /Research assessment relationships/); assert.ok(policyRoute.includes('import.meta.env.BASE_URL')); });
test('the analytical policy grouping is not presented as an official EU policy description', () => { assert.match(policyRoute, /organises the corpus analytically/); assert.doesNotMatch(policyRoute, /Official policy description/); });
